variables:
  IAC_IMAGE: ${CI_REGISTRY}/infra/iac-base:cecfa2a5
  NODE_VERSION: '12'
  ARTEFACT_KEY: poc-octovhs${CI_COMMIT_REF_SLUG}
  CACHE_KEY: 'poc-octovhs'

stages:
  - test
  - qualification
  - postqualification
  - production

test:
  stage: test
  image: node:${NODE_VERSION}-alpine
  cache:
    key: $CACHE_KEY
    paths:
      - node_modules/
    policy: pull-push

  script:
    - yarn
    - yarn test:ci
  coverage: /^All files\s*\|\s*([\d\.]+)/

lint:
  stage: test
  image: node:${NODE_VERSION}-alpine
  cache:
    key: $CACHE_KEY
    paths:
      - node_modules/
    policy: pull

  script:
    - yarn
    - yarn lint --no-fix

security:
  stage: test
  image: node:${NODE_VERSION}-alpine
  script:
    - yarn audit
  allow_failure: true

outdated:
  stage: test
  image: node:${NODE_VERSION}-alpine
  script:
    - yarn outdated
  allow_failure: true

qualification:
  stage: qualification
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_QUALIF_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master

lighthouse qua:
  image: markhobson/node-chrome
  stage: postqualification
  only:
    - master
  before_script:
    - npm i -g lighthouse
  script:
    - lighthouse --chrome-flags="--headless --no-sandbox" $QUALIF_URL --output html --output-path ./report.html
  artifacts:
    paths:
      - ./report.html
    expire_in: 1 month

webperf qua:
  stage: postqualification
  image: node:${NODE_VERSION}-alpine
  cache:
    key: $CACHE_KEY
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn
    - yarn webpagetest test $QUALIF_URL -k $WEBTEST_API_KEY -o ./webperf.html
  only:
    - master
  artifacts:
    paths:
      - ./webperf.html
    expire_in: 1 month

cost of module:
  stage: postqualification
  image: node:${NODE_VERSION}-alpine
  cache:
    key: $CACHE_KEY
    paths:
      - node_modules/
    policy: pull
  script:
    - yarn install
    - yarn cost
  only:
    - master
  when: manual

production:
  stage: production
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_PROD_APP_NAME --api-key=$HEROKU_API_KEY
  only:
    - master
  when: manual
